addSbtPlugin("com.github.cuzfrog" % "sbt-tmpfs" % "0.3.2")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.21")
//addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.0.0")
//addSbtPlugin("com.dwijnand" % "sbt-dynver" % "1.3.0")
//addSbtPlugin("me.lessis" % "bintray-sbt" % "0.3.0")
addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler" % "0.9.0")