package sri.web.vdom.styled

import org.scalajs.dom

import scala.scalajs.js
import scala.scalajs.js.|

/** The code is generated by sbt task. */
trait StyledAttributes {
  object defer {def :=(v: js.UndefOr[Boolean]): TypedProp[js.UndefOr[Boolean]] = DummyProp}

  object coords {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object span {def :=(v: js.UndefOr[Int]): TypedProp[js.UndefOr[Int]] = DummyProp}

  object method {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object keyType {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object challenge {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object name {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object formNoValidate {def :=(v: js.UndefOr[Boolean]): TypedProp[js.UndefOr[Boolean]] = DummyProp}

  object tabIndex {def :=(v: js.UndefOr[Int]): TypedProp[js.UndefOr[Int]] = DummyProp}

  object is {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object accept {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object loop {def :=(v: js.UndefOr[Boolean]): TypedProp[js.UndefOr[Boolean]] = DummyProp}

  object marginWidth {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object step {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object classID {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object size {def :=(v: js.UndefOr[Int]): TypedProp[js.UndefOr[Int]] = DummyProp}

  object optimum {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object readOnly {def :=(v: js.UndefOr[Boolean]): TypedProp[js.UndefOr[Boolean]] = DummyProp}

  object pattern {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object scrolling {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object nonce {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object cellSpacing {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object frameBorder {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object contentEditable {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object role {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object checked {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object acceptCharset {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object scope {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object icon {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object hrefLang {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object data {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object label {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object hidden {def :=(v: js.UndefOr[Boolean]): TypedProp[js.UndefOr[Boolean]] = DummyProp}

  object marginHeight {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object rel {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object height {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object radioGroup {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object min {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object selected {def :=(v: js.UndefOr[Boolean]): TypedProp[js.UndefOr[Boolean]] = DummyProp}

  object cellPadding {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object srcDoc {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object charSet {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object placeholder {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object open {def :=(v: js.UndefOr[Boolean]): TypedProp[js.UndefOr[Boolean]] = DummyProp}

  object inputMode {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object dateTime {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object crossOrigin {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object autoFocus {def :=(v: js.UndefOr[Boolean]): TypedProp[js.UndefOr[Boolean]] = DummyProp}

  object formTarget {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object poster {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object htmlFor {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object seamless {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object dir {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object low {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object id {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object async {def :=(v: js.UndefOr[Boolean]): TypedProp[js.UndefOr[Boolean]] = DummyProp}

  object wrap {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object autoComplete {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object max {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object profile {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object allowFullScreen {def :=(v: js.UndefOr[Boolean]): TypedProp[js.UndefOr[Boolean]] = DummyProp}

  object cite {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object draggable {def :=(v: js.UndefOr[Boolean]): TypedProp[js.UndefOr[Boolean]] = DummyProp}

  object alt {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object httpEquiv {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object formMethod {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object default {def :=(v: js.UndefOr[Boolean]): TypedProp[js.UndefOr[Boolean]] = DummyProp}

  object accessKey {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object className {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object srcLang {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object sandbox {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object src {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object encType {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object colSpan {def :=(v: js.UndefOr[Int]): TypedProp[js.UndefOr[Int]] = DummyProp}

  object content {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object mediaGroup {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object rowSpan {def :=(v: js.UndefOr[Int]): TypedProp[js.UndefOr[Int]] = DummyProp}

  object media {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object useMap {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object scoped {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object disabled {def :=(v: js.UndefOr[Boolean]): TypedProp[js.UndefOr[Boolean]] = DummyProp}

  object target {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object srcSet {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object minLength {def :=(v: js.UndefOr[Int]): TypedProp[js.UndefOr[Int]] = DummyProp}

  object spellCheck {def :=(v: js.UndefOr[Boolean]): TypedProp[js.UndefOr[Boolean]] = DummyProp}

  object shape {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object formEncType {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object sizes {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object manifest {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object multiple {def :=(v: js.UndefOr[Boolean]): TypedProp[js.UndefOr[Boolean]] = DummyProp}

  object kind {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object title {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object allowTransparency {def :=(v: js.UndefOr[Boolean]): TypedProp[js.UndefOr[Boolean]] = DummyProp}

  object lang {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object headers {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object `type` {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object form {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object required {def :=(v: js.UndefOr[Boolean]): TypedProp[js.UndefOr[Boolean]] = DummyProp}

  object href {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object start {def :=(v: js.UndefOr[Int]): TypedProp[js.UndefOr[Int]] = DummyProp}

  object capture {def :=(v: js.UndefOr[Boolean]): TypedProp[js.UndefOr[Boolean]] = DummyProp}

  object preload {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object rows {def :=(v: js.UndefOr[Int]): TypedProp[js.UndefOr[Int]] = DummyProp}

  object width {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object autoPlay {def :=(v: js.UndefOr[Boolean]): TypedProp[js.UndefOr[Boolean]] = DummyProp}

  object reversed {def :=(v: js.UndefOr[Boolean]): TypedProp[js.UndefOr[Boolean]] = DummyProp}

  object download {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object value {def :=(v: js.UndefOr[String | Double | Int]): TypedProp[js.UndefOr[String | Double | Int]] = DummyProp}

  object muted {def :=(v: js.UndefOr[Boolean]): TypedProp[js.UndefOr[Boolean]] = DummyProp}

  object noValidate {def :=(v: js.UndefOr[Boolean]): TypedProp[js.UndefOr[Boolean]] = DummyProp}

  object maxLength {def :=(v: js.UndefOr[Int]): TypedProp[js.UndefOr[Int]] = DummyProp}

  object action {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object summary {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object integrity {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object contextMenu {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object high {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object cols {def :=(v: js.UndefOr[Int]): TypedProp[js.UndefOr[Int]] = DummyProp}

  object formAction {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object list {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object keyParams {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object controls {def :=(v: js.UndefOr[Boolean]): TypedProp[js.UndefOr[Boolean]] = DummyProp}

  object amplitude {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object numOctaves {def :=(v: js.UndefOr[Int]): TypedProp[js.UndefOr[Int]] = DummyProp}

  object colorInterpolation {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object format {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object divisor {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object kernelUnitLength {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object floodColor {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object clipPathUnits {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object x {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object contentStyleType {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object begin {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object intercept {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object xlinkRole {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object maskUnits {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object accumulate {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object contentScriptType {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object k2 {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object in {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object textRendering {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object kernelMatrix {def :=(v: js.UndefOr[js.Array[Double]]): TypedProp[js.UndefOr[js.Array[Double]]] = DummyProp}

  object keyTimes {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object shapeRendering {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object dy {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object mask {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object pointsAtZ {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object seed {def :=(v: js.UndefOr[Int]): TypedProp[js.UndefOr[Int]] = DummyProp}

  object tableValues {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object overflow {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object xlinkShow {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object strokeDasharray {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object maskContentUnits {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object textAnchor {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object arabicForm {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object xlinkActuate {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object keyPoints {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object y {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object strokeOpacity {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object refY {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object viewBox {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object patternTransform {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object cx {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object textDecoration {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object scale {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object filterUnits {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object externalResourcesRequired {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object baseFrequency {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object g2 {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object stroke {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object clipPath {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object result {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object specularExponent {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object fillOpacity {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object horizOriginY {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object fontSizeAdjust {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object clipRule {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object limitingConeAngle {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object fx {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object additive {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object local {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object paintOrder {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object stopOpacity {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object colorInterpolationFilters {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object calcMode {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object refX {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object pointsAtY {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object repeatDur {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object dur {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object fontStyle {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object in2 {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object direction {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object enableBackground {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object pathLength {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object colorRendering {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object g1 {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object rx {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object specularConstant {def :=(v: js.UndefOr[Int]): TypedProp[js.UndefOr[Int]] = DummyProp}

  object x2 {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object viewTarget {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object exponent {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object cursor {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object radius {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object yChannelSelector {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object cy {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object xmlBase {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object to {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object attributeName {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object glyphRef {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object xmlSpace {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object filter {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object rotate {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object lengthAdjust {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object repeatCount {def :=(v: js.UndefOr[String | Int]): TypedProp[js.UndefOr[String | Int]] = DummyProp}

  object gradientTransform {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object fy {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object version {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object xlinkHref {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object markerWidth {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object fontFamily {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object gradientUnits {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object points {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object pointsAtX {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object kerning {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object offset {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object strokeDashoffset {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object horizOriginX {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object glyphOrientationHorizontal {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object elevation {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object letterSpacing {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object preserveAspectRatio {def :=(v: js.UndefOr[Boolean]): TypedProp[js.UndefOr[Boolean]] = DummyProp}

  object strokeLinecap {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object y1 {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object baseProfile {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object horizAdvX {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object wordSpacing {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object xmlLang {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object xChannelSelector {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object order {def :=(v: js.UndefOr[Int]): TypedProp[js.UndefOr[Int]] = DummyProp}

  object fill {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object systemLanguage {def :=(v: js.UndefOr[Boolean]): TypedProp[js.UndefOr[Boolean]] = DummyProp}

  object operator {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object by {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object origin {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object markerUnits {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object markerHeight {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object pointerEvents {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object floodOpacity {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object writingMode {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object patternContentUnits {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object xlinkType {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object xlinkArcrole {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object from {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object preserveAlpha {def :=(v: js.UndefOr[Boolean]): TypedProp[js.UndefOr[Boolean]] = DummyProp}

  object fontVariant {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object requiredExtensions {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object baselineShift {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object bias {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object requiredFeatures {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object fontSize {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object ry {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object mode {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object y2 {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object edgeMode {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object markerMid {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object startOffset {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object strokeMiterlimit {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object x1 {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object end {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object values {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object attributeType {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object k1 {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object targetY {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object glyphOrientationVertical {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object keySplines {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object opacity {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object markerStart {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object primitiveUnits {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object alignmentBaseline {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object patternUnits {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object surfaceScale {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object k4 {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object dx {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object allowReorder {def :=(v: js.UndefOr[Boolean]): TypedProp[js.UndefOr[Boolean]] = DummyProp}

  object r {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object clip {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object k3 {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object restart {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object fontStretch {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object imageRendering {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object stdDeviation {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object xlinkTitle {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object colorProfile {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object spacing {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object stopColor {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object strokeLinejoin {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object lightingColor {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object transform {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object fontWeight {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object diffuseConstant {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object visibility {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object unicodeBidi {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object targetX {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object strokeWidth {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object dominantBaseline {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object textLength {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object slope {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object azimuth {def :=(v: js.UndefOr[Double]): TypedProp[js.UndefOr[Double]] = DummyProp}

  object zoomAndPan {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object spreadMethod {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object markerEnd {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object z {def :=(v: js.UndefOr[String | Double]): TypedProp[js.UndefOr[String | Double]] = DummyProp}

  object display {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object fillRule {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object stitchTiles {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object d {def :=(v: js.UndefOr[String]): TypedProp[js.UndefOr[String]] = DummyProp}

  object onTimeUpdate {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onAnimationStart {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onKeyUp {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onDrag {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onCompositionStart {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onAnimationIteration {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onCanPlayThrough {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onDragStart {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onLoadStart {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onMouseUp {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onKeyPress {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onError {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onDragExit {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onSelect {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onCompositionEnd {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onTouchCancel {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onTouchEnd {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onTransitionEnd {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onSeeking {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onPlay {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onDoubleClick {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onDragOver {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onEnded {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onEmptied {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onMouseEnter {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onDragLeave {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onCompositionUpdate {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onMouseLeave {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onPlaying {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onMouseDown {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onSuspend {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onEncrypted {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onProgress {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onDurationChange {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onFocus {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onCut {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onSeeked {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onLoadedData {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onStalled {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onCanPlay {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onKeyDown {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onTouchStart {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onBlur {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onAbort {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onChange {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onVolumeChange {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onSubmit {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onLoadedMetadata {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onContextMenu {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onMouseMove {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onScroll {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onRateChange {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onAnimationEnd {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onWaiting {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onCopy {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onDragEnd {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onWheel {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onPause {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onDragEnter {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onClick {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onTouchMove {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onDrop {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onLoad {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onInput {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object onPaste {def :=(v: js.UndefOr[SyntheticEventCallback]): TypedProp[js.UndefOr[SyntheticEventCallback]] = DummyProp}

  object key {def :=(v: String | Int): TypedProp[String | Int] = DummyProp}

  object ref {def :=(v: js.Function1[_<:dom.Node, Unit]): TypedProp[js.Function1[_<:dom.Node, Unit]] = DummyProp}
}
